name: Run Docker in Docker
on:
  push:
    branches: ["main"]
jobs:
  test:
    runs-on: dind-latest
  steps:
    - name: Check Docker
      run: |
        which -a docker
        docker run --it alpine:latest 'echo hello from $hosname'
